from . import (product_template,
               product_attribute_value,
               fiber_family,
               properties,
               usage,
               product_type,
               structure,
               color_group,
               care_instructions,
               certification,
               product_template_attribute_line,
               available_meters,
               product_product,
               )
